{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "c99b1c6e",
   "metadata": {},
   "source": [
    "# Data Import"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "711c4352",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Import libraries\n",
    "import os\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "901d7836",
   "metadata": {},
   "outputs": [],
   "source": [
    "date = \"04-17-2025\"\n",
    "data_dict = {}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "c11cdd91",
   "metadata": {},
   "outputs": [],
   "source": [
    "graph_str     = \"../graphs/\" + date + \"/\"\n",
    "directory_str = \"../data/\" + date + \"/\"\n",
    "\n",
    "for dir in os.listdir(directory_str):\n",
    "    data_dict[dir] = []\n",
    "\n",
    "    tmp_graph_str     = graph_str + dir + \"/\"\n",
    "    tmp_directory_str = directory_str + dir + \"/\"\n",
    "\n",
    "    if os.path.isdir(tmp_graph_str) == False:\n",
    "        os.makedirs(tmp_graph_str)\n",
    "\n",
    "    for file in os.listdir(tmp_directory_str):\n",
    "        data_dict[dir].append(pd.read_csv(tmp_directory_str + file, delimiter=\";\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d71dbd1b",
   "metadata": {},
   "source": [
    "# Data Cleaning"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "dcaaa355",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_COL = \"Flow EZ #2 (12806) - Setpoint\"\n",
    "Y_COL = \"Flow Unit #1 [Flow EZ #1 (11411)]\"\n",
    "\n",
    "filtered_dict = {}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "df9b8fe8",
   "metadata": {},
   "outputs": [],
   "source": [
    "for key in data_dict.keys():\n",
    "    filtered_dict[key] = []\n",
    "\n",
    "    for df in data_dict[key]:\n",
    "        filtered_dict[key].append(df[[X_COL, Y_COL]])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "72510a74",
   "metadata": {},
   "source": [
    "# Functions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "12a90bf1",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "\n",
    "from typing import Tuple\n",
    "from scipy.stats import linregress\n",
    "from scipy.optimize import curve_fit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "5ab5d869",
   "metadata": {},
   "outputs": [],
   "source": [
    "def find_log_fit(df: pd.DataFrame) -> Tuple[str, float]:\n",
    "    \"\"\"\n",
    "    Use scipy to find the logarithmic fit and fitting parameters\n",
    "    \"\"\"\n",
    "\n",
    "    log_x = np.log(df[X_COL])\n",
    "    y = df[Y_COL]\n",
    "\n",
    "    a_log, b_log, r_log, _, _ = linregress(log_x, y)\n",
    "\n",
    "    df['log_fit'] = a_log * log_x + b_log\n",
    "\n",
    "    y_true     = df[Y_COL]\n",
    "    y_pred_log = df['log_fit']\n",
    "    ss_res_log = np.sum((y_true - y_pred_log) ** 2)\n",
    "    ss_tot_log = np.sum((y_true - np.mean(y_true)) ** 2)\n",
    "    r2_log = 1 - (ss_res_log / ss_tot_log)\n",
    "\n",
    "    if not np.isnan(a_log):\n",
    "        log_eq = (\n",
    "            f\"Log: y = {a_log:.3f} ln(x) + {b_log:.3f}\\n\"\n",
    "            f\"R² = {r2_log:.3f}\"\n",
    "        )\n",
    "    else:\n",
    "        df['log_fit'] = np.nan\n",
    "        log_eq = \"Logarithmic fit failed\"\n",
    "\n",
    "    return log_eq"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "395a33e6",
   "metadata": {},
   "outputs": [],
   "source": [
    "def find_logistic_fit(df: pd.DataFrame) -> Tuple[str, float]:\n",
    "    \"\"\"\n",
    "    Use scipy to find the logistic fit and fitting parameters\n",
    "    \"\"\"\n",
    "\n",
    "    # Logistic function definition\n",
    "    def logistic(x, L, k, x0):\n",
    "        return L / (1 + np.exp(-k * (x - x0)))\n",
    "    \n",
    "    # Initial parameter guess: [max y, slope, midpoint]\n",
    "    initial_guess = [df[Y_COL].max(), 1, df[X_COL].median()]\n",
    "\n",
    "    # Fit the logistic model\n",
    "    try:\n",
    "        params, _ = curve_fit(logistic, df[X_COL], df[Y_COL], p0=initial_guess, maxfev=10000)\n",
    "        L, k, x0_log = params\n",
    "        df['logistic_fit'] = logistic(df[X_COL], L, k, x0_log)\n",
    "        logistic_eq = f\"Logistic: y = {L:.2f} / (1 + e^(-{k:.2f}(x - {x0_log:.2f})))\"\n",
    "\n",
    "        # Calculate R²\n",
    "        y_true = df[Y_COL]\n",
    "        y_pred = df['logistic_fit']\n",
    "        ss_res = np.sum((y_true - y_pred) ** 2)\n",
    "        ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)\n",
    "        r2_logistic = 1 - (ss_res / ss_tot)\n",
    "\n",
    "        logistic_eq = (\n",
    "            f\"Logistic: y = {L:.2f} / (1 + e^(-{k:.2f}(x - {x0_log:.2f})))\\n\"\n",
    "            f\"R² = {r2_logistic:.3f}\"\n",
    "        )\n",
    "    except RuntimeError:\n",
    "        df['logistic_fit'] = np.nan\n",
    "        logistic_eq = \"Logistic fit failed\"\n",
    "\n",
    "    return logistic_eq"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "5b012d8d",
   "metadata": {},
   "outputs": [],
   "source": [
    "def find_lin_fit(df: pd.DataFrame) -> Tuple[str, float]:\n",
    "    \"\"\"\n",
    "    Use scipy to find the linear fit and fitting parameters\n",
    "    \"\"\"\n",
    "\n",
    "    a_lin, b_lin, r_lin, _, _ = linregress(df[X_COL], df[Y_COL])\n",
    "\n",
    "    df['lin_fit'] = a_lin * df[X_COL] + b_lin\n",
    "\n",
    "    y_true     = df[Y_COL]\n",
    "    y_pred_lin = df['lin_fit']\n",
    "    ss_res_lin = np.sum((y_true - y_pred_lin) ** 2)\n",
    "    ss_tot_lin = np.sum((y_true - np.mean(y_true)) ** 2)\n",
    "    r2_lin = 1 - (ss_res_lin / ss_tot_lin)\n",
    "\n",
    "    lin_eq = (\n",
    "        f\"Log: y = {a_lin:.3f} ln(x) + {b_lin:.3f}\\n\"\n",
    "        f\"R² = {r2_lin:.3f}\"\n",
    "    )\n",
    "\n",
    "    return lin_eq"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "1378ccb9",
   "metadata": {},
   "outputs": [],
   "source": [
    "def melt_data(df: pd.DataFrame) -> pd.DataFrame:\n",
    "    \"\"\"\n",
    "    Melt data for legend support\n",
    "    \"\"\"\n",
    "\n",
    "    df_melt = pd.melt(\n",
    "        df,\n",
    "        id_vars=[X_COL, Y_COL],\n",
    "        value_vars=['log_fit', 'lin_fit', 'logistic_fit'],\n",
    "        var_name='Fit Type',\n",
    "        value_name='Fit Value'\n",
    "    )\n",
    "\n",
    "    # Rename for legend\n",
    "    fit_labels = {'log_fit': 'Logarithmic Fit', 'lin_fit': 'Linear Fit', 'logistic_fit': 'Logistic Fit'}\n",
    "    df_melt['Fit Type'] = df_melt['Fit Type'].map(fit_labels)\n",
    "\n",
    "    return df_melt"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b7d7a15a",
   "metadata": {},
   "source": [
    "# Data Analysis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "390072c8",
   "metadata": {},
   "outputs": [],
   "source": [
    "from plotnine import (\n",
    "    ggplot,\n",
    "    aes,\n",
    "    geom_point,\n",
    "    geom_line,\n",
    "    ggtitle,\n",
    "    labs,\n",
    "    annotate,\n",
    "    xlim,\n",
    "    ylim,\n",
    "    scale_color_manual,\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "81c8db00",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_LABEL = \"Pressure In (mb)\"\n",
    "Y_LABEL = \"Flow Rate Out (µL/min)\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "0285c3a4",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\210766199.py:11: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\2236771600.py:8: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\4003656880.py:17: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:615: PlotnineWarning: Saving 10 x 6 in image.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:616: PlotnineWarning: Filename: ../graphs/4-17-2025/chip1/graph_0.png\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\layer.py:364: PlotnineWarning: geom_point : Removed 6 rows containing missing values.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\geoms\\geom_path.py:100: PlotnineWarning: geom_path: Removed 402 rows containing missing values.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\pandas\\core\\arraylike.py:399: RuntimeWarning: divide by zero encountered in log\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\numpy\\lib\\_function_base_impl.py:2888: RuntimeWarning: invalid value encountered in subtract\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\210766199.py:11: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\210766199.py:25: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\2236771600.py:8: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\4003656880.py:17: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:615: PlotnineWarning: Saving 10 x 6 in image.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:616: PlotnineWarning: Filename: ../graphs/4-17-2025/chip1/graph_1.png\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\layer.py:364: PlotnineWarning: geom_point : Removed 5724 rows containing missing values.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\geoms\\geom_path.py:100: PlotnineWarning: geom_path: Removed 1002 rows containing missing values.\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\210766199.py:11: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\2236771600.py:8: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\pandas\\core\\arraylike.py:399: RuntimeWarning: overflow encountered in exp\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\4003656880.py:17: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:615: PlotnineWarning: Saving 10 x 6 in image.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:616: PlotnineWarning: Filename: ../graphs/4-17-2025/chip2/graph_0.png\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\layer.py:364: PlotnineWarning: geom_point : Removed 6615 rows containing missing values.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\geoms\\geom_path.py:100: PlotnineWarning: geom_path: Removed 4807 rows containing missing values.\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\210766199.py:11: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\2236771600.py:8: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\4003656880.py:17: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:615: PlotnineWarning: Saving 10 x 6 in image.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:616: PlotnineWarning: Filename: ../graphs/4-17-2025/chip2/graph_1.png\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\layer.py:364: PlotnineWarning: geom_point : Removed 4056 rows containing missing values.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\pandas\\core\\arraylike.py:399: RuntimeWarning: divide by zero encountered in log\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\numpy\\lib\\_function_base_impl.py:2888: RuntimeWarning: invalid value encountered in subtract\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\210766199.py:11: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\210766199.py:25: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\2236771600.py:8: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\4003656880.py:17: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:615: PlotnineWarning: Saving 10 x 6 in image.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:616: PlotnineWarning: Filename: ../graphs/4-17-2025/chip3/graph_0.png\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\layer.py:364: PlotnineWarning: geom_point : Removed 15 rows containing missing values.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\pandas\\core\\arraylike.py:399: RuntimeWarning: divide by zero encountered in log\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\numpy\\lib\\_function_base_impl.py:2888: RuntimeWarning: invalid value encountered in subtract\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\210766199.py:11: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\210766199.py:25: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\2236771600.py:8: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\4003656880.py:17: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:615: PlotnineWarning: Saving 10 x 6 in image.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:616: PlotnineWarning: Filename: ../graphs/4-17-2025/chip3/graph_1.png\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\layer.py:364: PlotnineWarning: geom_point : Removed 33 rows containing missing values.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\pandas\\core\\arraylike.py:399: RuntimeWarning: divide by zero encountered in log\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\numpy\\lib\\_function_base_impl.py:2888: RuntimeWarning: invalid value encountered in subtract\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\210766199.py:11: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\210766199.py:25: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\2236771600.py:8: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\pandas\\core\\arraylike.py:399: RuntimeWarning: overflow encountered in exp\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\4003656880.py:17: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:615: PlotnineWarning: Saving 10 x 6 in image.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:616: PlotnineWarning: Filename: ../graphs/4-17-2025/chip3/graph_2.png\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\layer.py:364: PlotnineWarning: geom_point : Removed 4947 rows containing missing values.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\geoms\\geom_path.py:100: PlotnineWarning: geom_path: Removed 601 rows containing missing values.\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\210766199.py:11: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\2236771600.py:8: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\pandas\\core\\arraylike.py:399: RuntimeWarning: overflow encountered in exp\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\4003656880.py:15: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\4003656880.py:17: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:615: PlotnineWarning: Saving 10 x 6 in image.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:616: PlotnineWarning: Filename: ../graphs/4-17-2025/chip4/graph_0.png\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\layer.py:364: PlotnineWarning: geom_point : Removed 12084 rows containing missing values.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\geoms\\geom_path.py:100: PlotnineWarning: geom_path: Removed 11524 rows containing missing values.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\pandas\\core\\arraylike.py:399: RuntimeWarning: divide by zero encountered in log\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\numpy\\lib\\_function_base_impl.py:2888: RuntimeWarning: invalid value encountered in subtract\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\210766199.py:11: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\210766199.py:25: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\2236771600.py:8: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\pandas\\core\\arraylike.py:399: RuntimeWarning: overflow encountered in exp\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\4003656880.py:15: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "C:\\Users\\alper\\AppData\\Local\\Temp\\ipykernel_46196\\4003656880.py:17: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:615: PlotnineWarning: Saving 10 x 6 in image.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\ggplot.py:616: PlotnineWarning: Filename: ../graphs/4-17-2025/chip4/graph_1.png\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\layer.py:364: PlotnineWarning: geom_point : Removed 12015 rows containing missing values.\n",
      "c:\\Users\\alper\\Documents\\Code\\vips_data_analysis\\venv\\Lib\\site-packages\\plotnine\\geoms\\geom_path.py:100: PlotnineWarning: geom_path: Removed 10213 rows containing missing values.\n"
     ]
    }
   ],
   "source": [
    "for key in filtered_dict.keys():\n",
    "    df = pd.DataFrame()\n",
    "    chip_list = filtered_dict[key]\n",
    "\n",
    "    for i, df in enumerate(chip_list):\n",
    "        # Find applicable fits\n",
    "        log_eq      = find_log_fit(df)\n",
    "        lin_eq      = find_lin_fit(df)\n",
    "        logistic_eq = find_logistic_fit(df)\n",
    "\n",
    "        # Melt the data\n",
    "        df_melt = melt_data(df)\n",
    "\n",
    "        # Make the plot\n",
    "        plot =  (\n",
    "            ggplot(df_melt, aes(X_COL, Y_COL)) +\n",
    "            geom_point() +\n",
    "            geom_line(\n",
    "                aes(\n",
    "                    y='Fit Value',\n",
    "                    color='Fit Type'\n",
    "                )\n",
    "            ) +\n",
    "            scale_color_manual(\n",
    "                values = {\n",
    "                    'Logarithmic Fit': 'blue',\n",
    "                    'Linear Fit': 'red',\n",
    "                    'Logistic Fit': 'green'\n",
    "                }\n",
    "            ) +\n",
    "            ggtitle(f\"{Y_LABEL} vs {X_LABEL}\") +\n",
    "            labs(\n",
    "                x=X_LABEL,\n",
    "                y=Y_LABEL,\n",
    "                color=\"Model Fit\"\n",
    "            ) +\n",
    "            xlim(0, None) +\n",
    "            ylim(0, 400) +\n",
    "            annotate(\n",
    "                \"text\",\n",
    "                x=0,\n",
    "                y=400,\n",
    "                label=logistic_eq,\n",
    "                ha='left',\n",
    "                va='top',\n",
    "                size=8,\n",
    "                color='green'\n",
    "            ) +\n",
    "            annotate(\n",
    "                \"text\",\n",
    "                x=0,\n",
    "                y=350,\n",
    "                label=log_eq,\n",
    "                ha='left',\n",
    "                va='top',\n",
    "                size=8,\n",
    "                color='blue'\n",
    "            ) +\n",
    "            annotate(\n",
    "                \"text\",\n",
    "                x=0,\n",
    "                y=300,\n",
    "                label=lin_eq,\n",
    "                ha='left',\n",
    "                va='top',\n",
    "                size=8,\n",
    "                color='red'\n",
    "            )\n",
    "        )\n",
    "\n",
    "        # Save the plot\n",
    "        plot.save(graph_str + f\"{key}/graph_{i}.png\", width=10, height=6, dpi=300)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv (3.11.8)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
